### PR TITLE
Rename .object/.bashrc to David-ccl7x

### PR DESCRIPTION
**Pull request by tor-ornet**
Do not use this tool for violence, as I created it for people who are good at using it

### CODE REVIEW

**Comment by tor-ornet** [comment]
Do not use anything against violence and do not know what you will suffer in pain later from this thing

**Comment by tor-ornet** [comment]
Do not use anything against violence and do not know what you will suffer in pain later from this thing

**Comment by tor-ornet** [comment]
Hello I'm david and you?

**Comment by marzooq856** [comment]
i am marzooqshanu

**Pull request closed without merging**
